### PR TITLE
Fixed the example which was "The capital of India is #{capitals[India]}"...

### PR DESCRIPTION
**Pull request by floere**
... – my assumption is that this early on, we shouldn't get a constant error :)

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the quick fix.

**Comment by floere** [comment]
My pleasure. Btw, I found it through Matz tweet https://twitter.com/#!/yukihiro_matz/status/180069367638274048. Cheers!

**Comment by 0xfe** [comment]
On Wed, Mar 14, 2012 at 7:23 PM, Florian R. Hanke <
reply@reply.github.com

> wrote:
> 
> My pleasure. Btw, I found it through Matz tweet
> https://twitter.com/#!/yukihiro_matz/status/180069367638274048. Cheers!

Whoa! :-D

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/0xfe/rubyrefresher/pull/1#issuecomment-4510672

## 

Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by floere** [comment]
Glad to have pointed it out :)

**Pull request merged**
